Update xpm

diff --git a/airootfs/usr/local/bin/xpm b/airootfs/usr/local/bin/xpm
--- a/airootfs/usr/local/bin/xpm
+++ b/airootfs/usr/local/bin/xpm
@@ -6,13 +6,6 @@ if [[ $# -eq 0 ]]; then
   exit 0
 fi
 
-if [[ "$1" == "-i" ]]; then CMD="install"; shift; fi
-if [[ "$1" == "-r" ]]; then CMD="remove"; shift; fi
-if [[ "$1" == "-U" ]]; then CMD="upgrade"; shift; fi
-if [[ "$1" == "-u" ]]; then CMD="update"; shift; fi
-if [[ "$1" == "-s" ]]; then CMD="search"; shift; fi
-if [[ "$1" == "-h" ]]; then CMD="help"; shift; fi
-
 CMD="$1"
 shift
 PACKAGES=("$@")
@@ -125,7 +118,7 @@ if [[ -z "$CMD" ]]; then
 fi
 
 case "$CMD" in
-  install|add)
+  install|add|-i)
     if [[ "$1" == "-f" || "$1" == "--file" ]]; then
       shift
       for pkgfile in "$@"; do
@@ -147,10 +140,31 @@ case "$CMD" in
       done
     fi
     ;;
-  remove|delete)
+  installaur|-ia|addaur)
+    for pkg in "${PACKAGES[@]}"; do
+      echo "Wait for AUR checking... '$pkg'"
+      if [[ $EUID -eq 0 ]]; then
+        echo "AUR packages cannot be installed as root. Please run as a reguler user." >&2
+        exit 1
+      fi
+      aur_install "$pkg"
+      done
+    ;;
+  installarch|-iar|addarch)
+    for pkg in "${PACKAGES[@]}"; do
+      echo "Trying to install package '$pkg' from official repos..."
+      if sudo pacman -S --noconfirm "$pkg"; then
+        echo "Package '$pkg' installed successfully from official repo."
+      else
+	echo "Package '$pkg' could not be installed from official repo." >&2
+	exit 1
+      fi
+    done
+    ;;
+  remove|delete|-r)
     sudo pacman -R --noconfirm "${PACKAGES[@]}"
     ;;
-  upgrade)
+  upgrade|-U)
     if [[ ${#PACKAGES[@]} -eq 0 ]]; then
       sudo pacman -Syu --noconfirm
     else
@@ -160,10 +174,10 @@ case "$CMD" in
       done
     fi
     ;;
-  update)
+  update|-u)
     sudo pacman -Sy --noconfirm
     ;;
-  search)
+  search|-s)
     if [[ "${PACKAGES[1]}" == "-a" || "${PACKAGES[1]}" == "--aur" ]]; then
       query="${PACKAGES[0]}"
       echo "Searching AUR for '$query'..."
